# Site settings
title: Hussain Abbas
email: hussain@hussainabbas.com
description: Dabbler of Everything Technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hussainabbas.com" # the base hostname & protocol for your site

# Build settings
highlighter: true
markdown: kramdown
permalink: /blog/:title/
