# Site settings
title: Hussain Abbas | Front-End Engineer + Architect
email: howdy@hussainabbas.com
description: The portfolio site of Hussain Abbas, Front-End Engineer and Architect at Keyhole.co
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.hussainabbas.com" # the base hostname & protocol for your site

# Build settings
highlighter: pygments
markdown: kramdown
permalink: /blog/:title/

exclude: ["node_modules", "gulpfile.js", "package.json"]
