# Site settings
title: Hussain's Dev Playground
email: howdy@hussainabbas.com
description: Dabbler of Everything Technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hussainabbas.com" # the base hostname & protocol for your site

# Build settings
highlighter: pygments
markdown: kramdown
permalink: /blog/:title/

exclude: ["node_modules", "gulpfile.js", "package.json"]
